version: "3.7"

services:
  db:
    container_name: database
    image: postgres:11
    command: postgres -c log_destination=stderr -c log_statement=all -c log_connections=on -c log_disconnections=on
    environment:
      POSTGRES_USER: notera
      POSTGRES_PASSWORD: password
      POSTGRES_ROOT_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - notera

  data:
    container_name: data
    image: busybox
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - notera

volumes:
  db_data:

networks:
  notera:
    external: true
